### ISSUE TITLE
openxlsx reading issues

### ISSUE THREAD

**Issue by nevrome** [ropensci/c14bazAAR#105]
openxlsx seems to have problems with reading some files (see https://github.com/ycphs/openxlsx/issues/96).

One solution would be to read these files with the readxl package. That requires downloading the files to a tempdir first. If we use readxl I would suggest to replace openxlsx also in these instances where it works right now. So we should switch out openxlsx with readxl everywhere to keep the number of dependencies low.

**Comment by dirkseidensticker** [comment]
@nevrome as I got no comment on my issue https://github.com/ycphs/openxlsx/issues/96 by now, I will switch our codebase from `openxlsx::read.xlsx()` to `readxl::read_excel()`

**Comment by nevrome** [comment]
Excellent - thank you. I hope it's not too much work and goes smoothly.

**Comment by dirkseidensticker** [comment]
Noticed that [readxl](https://readxl.tidyverse.org/) can only read, but not write xlsx files; which we offer in `c14bazAAR::write_c14()`. This might be the reason why we switched to `openxlsx`. The readxl website promotes the [writexl](https://github.com/ropensci/writexl) package for writing xlsx files. Thus we would need to trade one package for two. But as readxl is part of tidyvers and writexl part of ropensci, we might see better support. @nevrome what do you think?

**Comment by nevrome** [comment]
Ja - let's go for readxl and writexl. The latter can go to the `Suggests` only and we can catch it with `check_if_packages_are_available()` in `write_c14()`.
