### ISSUE TITLE
get_neonet()

### ISSUE THREAD

**Issue by zoometh** [ropensci/c14bazAAR#162]
We have just completed collection of a new dataset, named NeoNet Atl, for Europe's South Atlantic river basins. This dataset complements the (first) NeoNet dataset focused on the river basins of the north-central and western Mediterranean (see [here](https://zoometh.github.io/neonet/)). NeoNet Atl dataset has exactly the same structure as the first NeoNet dataset already collected by `get_neonet()`. 
Is it worth creating a new function (`get_neonet_atl()`) or updating `get_neonet()` to collect both datasets?

**Comment by nevrome** [comment]
Hey @zoometh - good question. Maybe `radon` could serve as an example here. `radon` and `radonb` are also structurally identical and come from the same team. For them we had from the beginning two getter functions. So I think we could the same for `neonet` and `neonet_atl`. What do you think?

**Comment by zoometh** [comment]
@nevrome sorry for my late reply: Yes indeed, I'll prepare a `get_neonetb()`.

**Comment by nevrome** [comment]
Hey Thomas, I looked into the new setup more closely now and think the naming is not ideal. I think what I failed to communicate properly is that `radonb` is not just "version **b**" of radon, but a separate database for the **b**ronze age. So the **b** refers to that. I think we should therefore not distinguish `neonet` and `neonetb`, but `neonet` and `neonet???`, where `???` is up to you.

My understanding is, that `get_neonet()` now downloads a new version of the old dataset from the North Central-Western Mediterranean Basin, whereas `get_neonetb` downloads the first version of a new dataset from the Southern European Atlantic Coast (https://digitallib.unipi.it/it/raccolta/The-NeoNetAtl-dataset/). I thus suggest to rename `neonetb` to `neonetatl` as originally suggested by you, before I release a new version of c14bazAAR.

What do you think?

**Comment by zoometh** [comment]
Hi @nevrome. Yes, `neonetalt` would match perfectly

**Comment by zoometh** [comment]
Hi @nevrome, you can rename `neonetb` to `neonetatl` if you prefer. As you have noted, the distinction between the two datasets lies in their spatial extents, not their temporal extent (similar to `radon`).

**Comment by nevrome** [comment]
Done. I will now make a release :+1:
