### ISSUE TITLE
simple write_csv and write_xlsx functions

### ISSUE THREAD

**Issue by nevrome** [ropensci/c14bazAAR#39]
c14bazAAR should provide a simple but powerful function to write c14_date_lists to the file system.

**Comment by nmueller18** [comment]
Is this really necessary? I had good success with `write.table(x,file.choose(),sep="\t")`. The only precondition is that the file chosen must already exist (another thing for a possible vignette).

**Comment by nevrome** [comment]
The output of the calibration function contains a list column. `write.table()` can't deal with that in a good way.

**Comment by nevrome** [comment]
#84
