### ISSUE TITLE
Duplicate joining - 'dedubing'

### ISSUE THREAD

**Issue by MartinHinz** [ropensci/c14bazAAR#75]
Suggestion: a dedubing function like in Zotero:

![Bildschirmfoto von 2019-08-29 10-58-33](https://user-images.githubusercontent.com/3285169/63926340-fdbeab00-ca4b-11e9-9040-e99364b61e0f.png)

Just a suggestion... ;-)

**Comment by nevrome** [comment]
I believe this is interesting beyond the scope of c14bazAAR. One could make a shiny app or an RStudio addin that allows to do this for all sorts of data.frames. The duplicates could be indicated by a grouping column. Some kind of general interface for manual deduping.
