### ISSUE TITLE
Eubar parser: wrong coordinate is not removed by `coordinate_precision()`

### ISSUE THREAD

**Issue by dirkseidensticker** [ropensci/c14bazAAR#96]
Within the Eubar dataset one date (**Beta-206320**) is associated with an incorrect coordinate: lat = 4.112887 / lon = 2.591112 that place the date within the Atlantic Ocean, about 240 km south of Benin. The site has to be -- according to the county field -- in north-eastern Spain. This coord is already incorrect in the base dataset.

Should that not be corrected by this code?
```
c14.data <- get_c14data(databases = "eubar") %>%
  standardize_country_name() %>%
  determine_country_by_coordinate() %>%
  finalize_country_name() %>%
  coordinate_precision()
```

The 'correction' from *España* to *Spain* is listed in the [country_thesaurus.csv](https://github.com/ropensci/c14bazAAR/blob/master/data-raw/country_thesaurus.csv#L17), and `determine_country_by_coordinate()` returns *Benin* as `country_final`. What happens if there is a mismatch?

I figure such an issue should better the caught using an existing or new function, and rather not individually in the parser.

**Comment by nevrome** [comment]
Ok - these functions do exactly what they are supposed to. `standardize_country_name()` fixes the country name string. `determine_country_by_coordinate()` derives the country from the coordinates. `finalize_country_name()` merges this info and prefers the coordinate-based info. `coordinate_precision` is completely unrelated.

**Comment by nevrome** [comment]
One way to improve this, would be a console message or an additional column by `finalize_country_name()` in case of a mismatch between the country names.

**Comment by nevrome** [comment]
Maybe we should simplify this interface into one function. And `coordinate_precision()` is actually more confusing then helpful. Maybe we should remove it.

**Comment by dirkseidensticker** [comment]
> One way to improve this, would be a console message or an additional column by `finalize_country_name()` in case of a mismatch between the country names.

Okay, so in case of a mismatch between the standardized country names and the one's determined by using the coordinates, nothing happened thus far? 😕 

![Screenshot 2020-03-24 15 30 57](https://user-images.githubusercontent.com/6630811/77437124-92bc3380-6de4-11ea-8500-8b9621002a9b.png)

But still there seems to be an issue that `standardize_country_name()` is not respecting the `country_thesaurus`: while España is mapped to Spain in the (thesaurus)[https://github.com/ropensci/c14bazAAR/blob/master/data-raw/country_thesaurus.csv#L17], the function returns *Canada* 😮

**Comment by dirkseidensticker** [comment]
> Ok - these functions do exactly what they are supposed to. `standardize_country_name()` fixes the country name string. `determine_country_by_coordinate()` derives the country from the coordinates. `finalize_country_name()` merges this info and prefers the coordinate-based info. `coordinate_precision` is completely unrelated.

okay, I get the decision on why `finalize_country_name()` prefers the country name derived by the coordinates, but aren't the chances of errors bigger within the coord-set? Have we ever compared this?

**Comment by nevrome** [comment]
Never did any comparison here, Dirk. CalPal had lots of wrong country attributions while the coordinates seemed generally to have a higher accuracy. But we're far beyond CalPal now, so maybe we have to rethink this. My concerning is more to simplify this interface. We don't need three functions to fix country names, but one with a method parameter.

Could you do some digging, where this España -> Canada issue is coming from?

**Comment by dirkseidensticker** [comment]
> Never did any comparison here, Dirk. CalPal had lots of wrong country attributions while the coordinates seemed generally to have a higher accuracy. But we're far beyond CalPal now, so maybe we have to rethink this. My concern is more to simplify this interface. We don't need three functions to fix country names, but one with a method parameter.
> 
> Could you do some digging where this España -> Canada issue is coming from?

okay, I'll try to figure out where the issue is

**Comment by nevrome** [comment]
Hm - here's an idea how to simplify the country determination interface: 

- Deprecate `coordinate_precision()`: The initial idea was good, but the input data usually does not allow for a meaningful determination of precision. Many datapoints have absurdly high precision as an artifact of the way the site coordinates where entered (e.g. "clicking in Google Earth"). I therefore suggest to get rid of this feature to simplify the user interface and avoid confusion. @dakni: Would you be ok with that? Would you like to place this code somewhere else in another package?
- Deprecate `finalize_country_name()`: It only introduces a simple logic to merge `country_coord` and `country_thes` and `country`. I think it's actually more easy for the user to write this code himself if she wants it. Gives more power and control to the user and simplifies our interface.
- Rename `standardize_country_name()` to `fix_database_country_name()` to make it more clear what it does. It's actually equally unclear, but it sounds simpler. Does this make sense?

With these changes we would end up with only the two functions `determine_country_by_coordinate()` and `fix_database_country_name()`. The first adds a new column `country_coord` the latter a new column `country_thes`.

This does not fix wrong decisions of the algorithms, but makes it very clear which function does what.

**Comment by nevrome** [comment]
I think this issue can be closed, @dirkseidensticker. We made the interface more clear now and so far c14bazAAR just does not have a function to identify obviously wrong coordinates like the ones of **Beta-206320**. And it would be very difficult to come up with one. So I think we did what we could.
